import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans, Source_Sans_3 } from 'next/font/google';

import { ThemeProvider } from '@/components/theme/ThemeProvider';

const open = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open',
});

const source = Source_Sans_3({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-source',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open.variable} ${source.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
